apiVersion: batch/v1
kind: CronJob
metadata:
  name: hls2mpeg
spec:
  schedule: "1 15 * * *"
  concurrencyPolicy: "Allow"
  jobTemplate:
    spec:
      parallelism: 1
      completions: 3 # set over count of cameras
      template:
        metadata:
          name: hls2mpeg
        spec:
          restartPolicy: OnFailure
          containers:
            - name: hls2mpeg
              image: registry.neko.lab:5005/root/monitoring/hls2mpeg
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 300m
                  memory: 800Mi
              volumeMounts:
                - name: video-out
                  mountPath: /out
              lifecycle:
                preStop:
                  exec:
                    command: ["/app/sigterm.sh"]
          volumes:
            - name: video-out
              glusterfs:
                endpoints: glusterfs-cluster
                path: /gvol/Data/camera
                readOnly: false
