apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-server
spec:
  selector:
    matchLabels:
      app: streaming-server
  template:
    metadata:
      labels:
        app: streaming-server
    spec:
      nodeSelector:
        device: camera
      containers:
        - name: streaming-server
          imagePullPolicy: Always
          image: registry.neko.lab:5005/root/monitoring/streaming-server
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: streaming-server
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.3.203
  selector:
    app: streaming-server
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
      name: http
