FROM alpine:3.14.3

WORKDIR /workspace
ENV TZ=Asia/Tokyo
ENV DEBIAN_FRONTEND=noninteractive

RUN apk add --no-cache --update --virtual builder git cmake make build-base clang && \ 
    apk add --no-cache --update live-media-dev libressl-dev linux-headers && \ 
    git clone -b v0.2.4 https://github.com/mpromonet/v4l2rtspserver.git && \ 
    cd ./v4l2rtspserver && \ 
    cmake . && \ 
    make install && \ 
    cd .. && \ 
    rm -rvf v4l2rtspserver && \ 
    apk del builder 

EXPOSE 8554
ENTRYPOINT ["v4l2rtspserver"]
